# Generated by Django 5.2.16 on 2026-08-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_community_adminaction_fakeaccountflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='nid_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
