# Generated by Django 5.2.16 on 2026-08-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donorprofile_nid_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='club_members/')),
            ],
        ),
        migrations.CreateModel(
            name='LocalClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='club_covers/')),
                ('president_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('president_photo', models.ImageField(blank=True, null=True, upload_to='club_members/')),
                ('total_donors', models.CharField(default='0', max_length=50)),
                ('active_donors', models.CharField(default='0', max_length=50)),
                ('contributions', models.CharField(default='0', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('accreditation', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner_images/')),
                ('stock_status', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NationalCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('active_donors', models.CharField(default='0', max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='community_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Upazila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.AddField(
            model_name='district',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api.division'),
        ),
        migrations.AddField(
            model_name='localclub',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district'),
        ),
        migrations.AddField(
            model_name='localclub',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.division'),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_members', to='api.localclub'),
        ),
        migrations.AddField(
            model_name='upazila',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upazilas', to='api.district'),
        ),
        migrations.AddField(
            model_name='localclub',
            name='upazila',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.upazila'),
        ),
    ]
