# Generated by Django 5.2.16 on 2026-08-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_district_division_executivemember_localclub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodScienceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='health_hub/science/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5, unique=True)),
                ('can_give_to', models.CharField(max_length=50)),
                ('can_receive_from', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DonationGuideSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('eligibility', 'Eligibility Basics'), ('journey', 'The Donation Journey'), ('myth', 'Myths vs Facts'), ('preparation', 'Preparation Tips'), ('why_donate', 'Why Donate?')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_24_hours', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryTimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_mark', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_guideline', models.CharField(blank=True, max_length=255)),
                ('avoid_list', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['hour_mark'],
            },
        ),
    ]
