# Generated by Django 5.2.16 on 2026-08-29 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bloodsciencearticle_compatibilityrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='bio',
            field=models.TextField(blank=True, help_text="User's biography or story.", null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='institute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='manual_rank_override',
            field=models.CharField(blank=True, help_text='Admin override for badge (e.g. Gold, Platinum).', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='total_bags_donated',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DonationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('bags_donated', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_history', to='api.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RecentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('DONATION', 'Donation'), ('REQUEST', 'Request'), ('VERIFICATION', 'Verification'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_success', models.BooleanField(default=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_logs', to='api.donorprofile')),
            ],
        ),
    ]
