# Generated by Django 5.2.16 on 2026-09-16 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_localclub_status_registered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(default='Local Blood Guide', max_length=150)),
                ('area_name', models.CharField(default='Uttara, Dhaka', max_length=150)),
                ('phone', models.CharField(default='+8801700000000', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='area_guides/')),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.division')),
                ('upazila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.upazila')),
            ],
        ),
    ]
