# Generated by Django 5.2.16 on 2026-09-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_area_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
