# Generated by Django 5.2.16 on 2026-09-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_socialpost_original_post_comment_postreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
