# Generated by Django 5.2.16 on 2026-09-24 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_donorprofile_email_verified_emailverificationcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='attendant_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='client_request_id',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='component',
            field=models.CharField(default='WHOLE', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='condition_category',
            field=models.CharField(default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='condition_note',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='current_wave',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.division'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='effective_scope',
            field=models.CharField(default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='escalated_to_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='geohash',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requests', to='api.hospital'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital_name_other',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='is_drill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='mode',
            field=models.CharField(default='EMERGENCY', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='next_wave_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='patient_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='requisition_slip',
            field=models.FileField(blank=True, null=True, upload_to='requisition_slips/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='scope',
            field=models.CharField(default='LOCAL', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='trust_band',
            field=models.CharField(default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='trust_score',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.upazila'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(default='CRITICAL_2H', max_length=20),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='ward_bed',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='alert_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='alert_pause_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='campus',
            field=models.CharField(blank=True, default='', help_text='Campus or institutional affiliation', max_length=255),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='cancel_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='deferral_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='fulfilled_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='geohash',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='is_searchable',
            field=models.BooleanField(default=False, help_text='Opt-in to donor search and map discovery'),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_lat',
            field=models.FloatField(blank=True, help_text='Fuzzed latitude for privacy (~500m)', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='last_lng',
            field=models.FloatField(blank=True, help_text='Fuzzed longitude for privacy (~500m)', null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='rating_avg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='response_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='api.division'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_bn',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hospital',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hospital',
            name='upazila',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='api.upazila'),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital_location',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency_level',
            field=models.CharField(default='CRITICAL_2H', max_length=50),
        ),
        migrations.CreateModel(
            name='DeferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('reason_code', models.CharField(choices=[('MEDICAL', 'Medical Rejection'), ('TIMEFRAME', 'Donation Interval Cooldown'), ('TRAVEL', 'Travel / Endemic Zone'), ('OTHER', 'Other')], default='MEDICAL', max_length=20)),
                ('starts_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('appeal_status', models.CharField(default='NONE', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deferrals', to='api.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave', models.PositiveIntegerField(default=1)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_notifications', to='api.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.bloodrequest')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FakeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Fake'), ('DISMISSED', 'Dismissed / Valid')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fake_reports', to='api.bloodrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On the Way'), ('ARRIVED', 'Arrived at Hospital'), ('DONATED', 'Donation Completed'), ('FAILED', 'Failed / Cancelled'), ('CANCELLED', 'Cancelled by Requester')], default='ACCEPTED', max_length=20)),
                ('is_standby', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='api.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='api.bloodrequest')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_requests', to='api.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.bloodrequest')),
            ],
            options={
                'unique_together': {('request', 'donor')},
            },
        ),
    ]
