# Generated by Django 5.2.16 on 2026-09-24 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_bloodrequest_attendant_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='donor_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='donor_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='eta_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DonationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('MEDICAL_REJECTION', 'Medical Rejection (Low Hb, Vein, Vitals)'), ('DONOR_NO_SHOW', 'Donor No-Show / Unreachable'), ('LOGISTICS_DELAY', 'Logistics / Traffic Delay'), ('OTHER', 'Other Issue')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acceptance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='api.requestacceptance')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StandbyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Offer'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Offer Expired')], default='PENDING', max_length=20)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_offers', to='api.donorprofile')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standby_offers', to='api.bloodrequest')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
    ]
