# Generated by Django 5.2.16 on 2026-09-24 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_emailotp_requestacceptance_distance_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisasterResponsePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_camp', models.BooleanField(default=False)),
                ('target_bags', models.PositiveIntegerField(default=100)),
                ('collected_bags', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NEEDED', 'Needed'), ('PARTIAL', 'Partial'), ('COVERED', 'Covered')], default='NEEDED', max_length=20)),
                ('urgent_blood_groups', models.JSONField(default=list)),
                ('donors_on_the_way', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NationalEmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('description_en', models.TextField(blank=True)),
                ('description_bn', models.TextField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='emergency_posters/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('donation_interval_days', models.PositiveIntegerField(default=90)),
                ('instructions_en', models.TextField(blank=True)),
                ('instructions_bn', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_range', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('pledged', models.PositiveIntegerField(default=0)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='api.disasterresponsepoint')),
            ],
        ),
        migrations.AddField(
            model_name='disasterresponsepoint',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.nationalemergencyevent'),
        ),
        migrations.CreateModel(
            name='DisasterPledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_code', models.CharField(max_length=10, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disaster_pledges', to='api.donorprofile')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='api.donationslot')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='api.nationalemergencyevent')),
            ],
        ),
    ]
