# Generated by Django 5.2.16 on 2026-09-24 20:13

import api.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_medicalknowledgebase_chatmessage_supportticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='nid_hash',
            field=api.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
