# Generated by Django 5.2.16 on 2026-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=100)),
                ('description_en', models.TextField()),
                ('description_bn', models.TextField(blank=True, null=True)),
                ('affiliate_url', models.URLField(max_length=500)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('price_range_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
