# Generated by Django 5.2.16 on 2026-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_healthaccessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token', max_length=255, null=True),
        ),
    ]
