# Generated by Django 5.2.16 on 2026-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_donorprofile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestacceptance',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestacceptance',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
