# Generated by Django 5.2.16 on 2026-09-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_requestacceptance_auto_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='geohash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
    ]
