# Generated by Django 5.2.16 on 2026-09-26 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_donorprofile_geohash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaveEscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_wave', models.PositiveIntegerField()),
                ('to_wave', models.PositiveIntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=255)),
                ('new_radius_km', models.FloatField()),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wave_logs', to='api.bloodrequest')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Null if System triggered', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
