# Generated by Django 5.2.16 on 2026-09-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_waveescalationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_score', models.IntegerField(default=50)),
                ('hospital_verified', models.IntegerField(default=15)),
                ('prescription_slip', models.IntegerField(default=20)),
                ('no_show_penalty', models.IntegerField(default=25)),
            ],
        ),
    ]
