# Generated by Django 5.2.16 on 2026-09-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_trustscoreconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
