# Generated by Django 5.2.16 on 2026-09-27 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('eiin', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('institution_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('madrasa', 'Madrasa'), ('university', 'University')], max_length=50)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='api.district')),
            ],
        ),
    ]
