# Generated by Django 5.2.16

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_institution_upazila'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='reset_token',
        ),
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='code_hash',
            new_name='otp_hash',
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.RenameField(
            model_name='passwordresetotp',
            old_name='used',
            new_name='is_used',
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='last_sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]

