# Generated by Django 5.2.16 on 2026-09-30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_passwordresetotp_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='auth_provider',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
