# Generated by Django 5.2.16 on 2026-09-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_passwordresetotp_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminbroadcast',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='healthaccessory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicalknowledgebase',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='trustscoreconfig',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='waveescalationlog',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='disasterpledge',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterpledge',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='auth_provider',
            field=models.CharField(default='credentials', max_length=50),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='google_uid',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fakereport',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fakereport',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttarget',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesttarget',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standbyoffer',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standbyoffer',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='geohash',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='nid_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='SupportTicket',
        ),
    ]
