# Generated by hand for additive fulfillment fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_google_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterpledge',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='disasterpledge',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fakereport',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fakereport',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requesttarget',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requesttarget',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standbyoffer',
            name='auto_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='standbyoffer',
            name='donated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
