# Generated by Django 5.2.16 on 2026-09-30 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_adminbroadcast_options_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminbroadcast',
            table='api_adminbroadcast',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='api_auditlog',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table='api_supportticket',
        ),
        migrations.AlterModelTable(
            name='healthaccessory',
            table='api_healthaccessory',
        ),
        migrations.AlterModelTable(
            name='medicalknowledgebase',
            table='api_medicalknowledgebase',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='api_notification',
        ),
        migrations.AlterModelTable(
            name='trustscoreconfig',
            table='api_trustscoreconfig',
        ),
        migrations.AlterModelTable(
            name='waveescalationlog',
            table='api_waveescalationlog',
        ),
    ]
