import 'package:flutter/material.dart';

/// Model representing a curated blood and health accessory.
class HealthAccessory {
  final String id;
  final String title;
  final String category; // 'Consumables' | 'Diagnostic & Clinic' | 'Parts & Kits' | 'Donor Gear'
  final String tier;
  final String description;
  final String priceRange;
  final double rating;
  final int reviewsCount;
  final String affiliateUrl;
  final String storeName;
  final IconData icon;
  final Color accentColor;
  final Color bgLightColor;

  const HealthAccessory({
    required this.id,
    required this.title,
    required this.category,
    required this.tier,
    required this.description,
    required this.priceRange,
    required this.rating,
    required this.reviewsCount,
    required this.affiliateUrl,
    required this.storeName,
    required this.icon,
    this.accentColor = const Color(0xFFC30121),
    this.bgLightColor = const Color(0xFFFFF0F1),
  });

  /// Curated catalogue directly synchronized with BloodPulse Stitch UI Screen:
  /// 'Health & Blood Accessories' (Screen ID: a60dff7c188e4fdf92dc4b48392ad450)
  static const List<HealthAccessory> curatedList = [
    HealthAccessory(
      id: 'acc_1',
      title: 'Digital Blood Pressure (BP) Monitor (Arm/Wrist)',
      category: 'Diagnostic & Clinic',
      tier: 'Tier 2: Diagnostic',
      description: 'Certified oscillometric upper arm cuff with irregular heartbeat detection, dual-user memory, and high-contrast LCD readout.',
      priceRange: '৳2,200 - ৳3,800',
      rating: 4.8,
      reviewsCount: 342,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=digital+blood+pressure+monitor',
      storeName: 'Daraz MedStore',
      icon: Icons.monitor_heart_outlined,
      accentColor: Color(0xFF0D68AA),
      bgLightColor: Color(0xFFEDF4FF),
    ),
    HealthAccessory(
      id: 'acc_2',
      title: 'Fingertip Pulse Oximeter (SpO2 & Pulse Tracker)',
      category: 'Diagnostic & Clinic',
      tier: 'Tier 2: Diagnostic',
      description: 'Medical-grade photoelectric sensor measuring SpO2 arterial oxygen saturation and PR blood pulse rate in under 5 seconds.',
      priceRange: '৳850 - ৳1,500',
      rating: 4.7,
      reviewsCount: 215,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=pulse+oximeter',
      storeName: 'Daraz MedStore',
      icon: Icons.bloodtype_outlined,
      accentColor: Color(0xFFC30121),
      bgLightColor: Color(0xFFFFF0F1),
    ),
    HealthAccessory(
      id: 'acc_3',
      title: 'Blood Glucose Test Strips & Lancets (Pack of 50–100)',
      category: 'Consumables',
      tier: 'Tier 1: Consumables',
      description: 'Ultra-thin gold electrode strips requiring minimal capillary sample (0.5µL) for fast, painless blood chemistry testing.',
      priceRange: '৳650 - ৳1,200',
      rating: 4.9,
      reviewsCount: 520,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=glucose+test+strips+lancets',
      storeName: 'Apollo Health',
      icon: Icons.biotech_outlined,
      accentColor: Color(0xFFE65100),
      bgLightColor: Color(0xFFFFF3E0),
    ),
    HealthAccessory(
      id: 'acc_4',
      title: 'Iron + Folic Acid Donor Recovery Booster',
      category: 'Consumables',
      tier: 'Tier 1: Consumables',
      description: 'Chelated ferrous bisglycinate with Vitamin C and methylfolate to restore hemoglobin levels rapidly post-donation without nausea.',
      priceRange: '৳450 - ৳900',
      rating: 4.8,
      reviewsCount: 184,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=iron+folic+acid+supplement',
      storeName: 'Square Pharma Care',
      icon: Icons.medication_outlined,
      accentColor: Color(0xFF1B8A4E),
      bgLightColor: Color(0xFFE8F5E9),
    ),
    HealthAccessory(
      id: 'acc_5',
      title: 'Quick-Release Phlebotomy Tourniquet Band',
      category: 'Parts & Kits',
      tier: 'Tier 3: Parts & Kits',
      description: 'Elastic cotton latex-free band with quick-release buckle designed for gentle venous occlusion during emergency phlebotomy.',
      priceRange: '৳120 - ৳250',
      rating: 4.6,
      reviewsCount: 96,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=phlebotomy+tourniquet',
      storeName: 'MedTech BD',
      icon: Icons.cable_outlined,
      accentColor: Color(0xFF6A1B9A),
      bgLightColor: Color(0xFFF3E5F5),
    ),
    HealthAccessory(
      id: 'acc_6',
      title: 'Adjustable Lancing Device Pen',
      category: 'Parts & Kits',
      tier: 'Tier 3: Parts & Kits',
      description: 'Precision depth adjustment dial (1 to 5 levels) minimizing puncture pain for regular capillary blood sampling and hemoglobin checks.',
      priceRange: '৳250 - ৳450',
      rating: 4.7,
      reviewsCount: 140,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=lancing+pen+device',
      storeName: 'Daraz MedStore',
      icon: Icons.colorize_outlined,
      accentColor: Color(0xFF00796B),
      bgLightColor: Color(0xFFE0F2F1),
    ),
    HealthAccessory(
      id: 'acc_7',
      title: 'Replacement Arm Cuffs & Bladders for BP Machines',
      category: 'Parts & Kits',
      tier: 'Tier 3: Parts & Kits',
      description: 'Universal 22-48cm extra-wide nylon cuff compatible with all standard digital and aneroid blood pressure monitoring units.',
      priceRange: '৳450 - ৳850',
      rating: 4.5,
      reviewsCount: 78,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=blood+pressure+monitor+cuff',
      storeName: 'MedTech BD',
      icon: Icons.tune_outlined,
      accentColor: Color(0xFF37474F),
      bgLightColor: Color(0xFFECEFF1),
    ),
    HealthAccessory(
      id: 'acc_8',
      title: 'Blood Group / Voluntary Donor Silicone Wristband',
      category: 'Donor Gear',
      tier: 'Tier 4: Donor Gear',
      description: 'Hypoallergenic debossed silicone identification bracelet displaying blood type (A+, B+, O+, AB-) for emergency responder awareness.',
      priceRange: '৳80 - ৳150',
      rating: 4.9,
      reviewsCount: 310,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=blood+group+wristband',
      storeName: 'BloodPulse Store',
      icon: Icons.watch_outlined,
      accentColor: Color(0xFFC30121),
      bgLightColor: Color(0xFFFFF0F1),
    ),
    HealthAccessory(
      id: 'acc_9',
      title: 'Red Drop Enamel Donor Pin & Badge Reel',
      category: 'Donor Gear',
      tier: 'Tier 4: Donor Gear',
      description: 'Gold-plated zinc alloy enamel badge with "Be A Lifesaver" insignia for regular donors, volunteers, and medical staff.',
      priceRange: '৳150 - ৳300',
      rating: 4.9,
      reviewsCount: 175,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=blood+donor+pin+badge',
      storeName: 'BloodPulse Store',
      icon: Icons.military_tech_outlined,
      accentColor: Color(0xFFC30121),
      bgLightColor: Color(0xFFFFF0F1),
    ),
    HealthAccessory(
      id: 'acc_10',
      title: 'Compact Hemostatic Emergency First Aid Kit',
      category: 'Consumables',
      tier: 'Tier 1: Consumables',
      description: 'Travel-ready medical pouch containing coagulant gauze, antiseptic wipes, sterile dressings, and CPR face shield for trauma response.',
      priceRange: '৳750 - ৳1,600',
      rating: 4.9,
      reviewsCount: 260,
      affiliateUrl: 'https://www.daraz.com.bd/catalog/?q=emergency+first+aid+kit',
      storeName: 'Apollo Health',
      icon: Icons.medical_services_outlined,
      accentColor: Color(0xFFC30121),
      bgLightColor: Color(0xFFFFF0F1),
    ),
  ];
}
