# Generated by Django 5.2.16 on 2026-09-24 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(max_length=10)),
                ('answer_json', models.JSONField()),
                ('kb_version', models.CharField(max_length=100)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AppGuideEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('body_en', models.TextField(help_text='Max 120 words')),
                ('body_bn', models.TextField(help_text='Max 120 words')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('logging_consent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('text_redacted', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('tokens_in', models.IntegerField(default=0)),
                ('tokens_out', models.IntegerField(default=0)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('latency_ms', models.IntegerField(default=0)),
                ('kb_ids_used', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.assistantconversation')),
            ],
        ),
        migrations.CreateModel(
            name='KBEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=200)),
                ('title_bn', models.CharField(max_length=200)),
                ('body_en', models.TextField(help_text='Max 120 words')),
                ('body_bn', models.TextField(help_text='Max 120 words')),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], max_length=10)),
                ('reason', models.CharField(blank=True, choices=[('WRONG', 'Wrong'), ('UNCLEAR', 'Unclear'), ('UNSAFE', 'Unsafe'), ('OTHER', 'Other')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assistant.assistantmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('contact_preference', models.CharField(choices=[('IN_APP', 'In App'), ('EMAIL', 'Email'), ('PHONE', 'Phone')], max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
