// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEwLrHATWvcr-JNKxun99Y74YDrhqiNCA',
    appId: '1:404989190662:android:4f22536e4a57c949e25987',
    messagingSenderId: '404989190662',
    projectId: 'bloodpulse-283dc',
    storageBucket: 'bloodpulse-283dc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWTbP-HY9qzyEXY76aOXQywg_lxyDmveY',
    appId: '1:404989190662:ios:57b7b9a8eb0aebe2e25987',
    messagingSenderId: '404989190662',
    projectId: 'bloodpulse-283dc',
    storageBucket: 'bloodpulse-283dc.firebasestorage.app',
    iosBundleId: 'com.example.bloodPulse',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCShzXhwOg-dzviWjcXMylDyWREU-HrVcU',
    appId: '1:404989190662:web:d93054d0554ce384e25987',
    messagingSenderId: '404989190662',
    projectId: 'bloodpulse-283dc',
    authDomain: 'bloodpulse-283dc.firebaseapp.com',
    storageBucket: 'bloodpulse-283dc.firebasestorage.app',
    measurementId: 'G-YF60Y0LHDB',
  );
}
